# Site settings
title: JUnit
email: team@junit.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://junit.org" # the base hostname & protocol for your site
current_repo_url: https://github.com/junit-team/junit-framework

# Build settings
markdown: kramdown
exclude:
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
